---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-capstone
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b"]    

managedNodeGroups:
  - name: udacity-capstone-1
    instanceType: t2.micro
    desiredCapacity: 3
    availabilityZones: ["us-east-1a"]   